# Generated by Django 2.0.8 on 2018-08-15 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('kode_barang', models.CharField(default='-', editable=False, max_length=30)),
                ('nama_barang', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=250, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='barang.Post')),
            ],
        ),
    ]
