# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0008_auto_20180515_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deskripsi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
