# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('kode_barang', models.CharField(editable=False, max_length=30)),
                ('nama_barang', models.CharField(max_length=30)),
                ('deskripsi', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nama_kategori', models.CharField(max_length=30)),
                ('deskripsi_kategori', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latihanapi.PostCategory'),
        ),
    ]
