# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0006_auto_20180515_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kodebarang',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
