# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0004_auto_20180515_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='updated_at',
        ),
    ]
