# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0010_auto_20180515_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
