# Generated by Django 2.1 on 2018-08-06 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('kodebarang', models.CharField(editable=False, max_length=30)),
                ('namabarang', models.CharField(max_length=30)),
                ('deskripsi', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(editable=False, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
